name: "beta"
on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags-ignore:        
      - 'v*'

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: install dependencies (ubuntu only)
      if: matrix.platform == 'ubuntu-20.04'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
    - name: Dynamically set BETA_TAG environment variable (not windows)
      if: runner.os != 'Windows'
      run: |
        echo "BETA_TAG=beta-$(git show -s --format=%cd-%h --date=format:'%Y-%m-%d' HEAD)"
        echo "BETA_TAG=beta-$(git show -s --format=%cd-%h --date=format:'%Y-%m-%d' HEAD)" >> $GITHUB_ENV
    - name: Dynamically set BETA_TAG environment variable (windows)
      if: runner.os == 'Windows'
      run: |
        chcp 65001 #set code page to utf-8
        $gitout = & git show -s --format=%cd-%h --date=format:'%Y-%m-%d' HEAD
        echo ("BETA_TAG=beta-" + $gitout)
        echo ("BETA_TAG=beta-" + $gitout) >> $env:GITHUB_ENV
    - uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tagName: ${{ env.BETA_TAG }}
        releaseName: ${{ env.BETA_TAG }}
        releaseBody: "See the assets to download this version and install."
        releaseDraft: false
        prerelease: true
